name: Clean

on:
  schedule:
    - cron:  '0 0 * * *'    # At every day

jobs:

  Clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: give premissions
      run: chmod +x cleanup.sh
        
    - name: Run cleanup
      run: ./cleanup.sh

  
