# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GO Build Advanced

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unit-tests-job:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: ['1.20', '1.19']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.version }}'

    - name: Test
      run: go test sum_test.go sum.go

  build-job:
    runs-on: ubuntu-latest
    needs: unit-tests-job
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build sum.go

    - name: list
      run: ls -l
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sum
        path: ./sum

  test_bin_job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:

    - name: Get the binary
      uses: actions/download-artifact@v3
      with:
        name: sum
        path: .

    - run: chmod +x ./sum

    # step that tests the binary output is 15 or not
    - name: Test
      run: ./sum 1 2 3 4 5 | grep 15



  docker_image_build_and_push:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/sum:latest
        file: ./Dockerfile