# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: my-go-project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test sum_test.go sum.go

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build sum.go

    - name: list
      run: ls -l

  # test_bin:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #  # get the binary from the build job
  #   - name: Get the binary
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: sum
  #   - uses: actions/checkout@v3

  #   - name: Test
  #     run: ./sum 1 2 3 4 5
