name: Go

on:
  push:
    branches: [ "main" ]
    paths:
     - '**.go'
 

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

  Deploy:
      needs: build
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2 
        - name: Deploy in EC2
          env:
              PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
              HOSTNAME : ${{ secrets.HOSTNAME  }}
              USER_NAME : ${{ secrets.USER_NAME  }}
              
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
  
